services:
  discovery-service:
    build:
      context: ./discovery-service # Ruta donde está el Dockerfile del config-server
      dockerfile: Dockerfile
    container_name: discovery-service
    ports:
      - "8761:8761" # Mapea el puerto 8761 del contenedor al puerto 8761 de tu máquina local
    networks:
      - app-network
    environment:
      SPRING_PROFILES_ACTIVE: local # Perfil activo en application.properties
      EUREKA_CLIENT_REGISTER_WITH_EUREKA: false
      EUREKA_CLIENT_FETCH_REGISTRY: false

  config-server-bc:
    build:
      context: ./config-server-bc # Ruta donde está el Dockerfile del config-server
      dockerfile: Dockerfile
    container_name: config-server-bc
    ports:
      - "8888:8888" # Mapea el puerto 8888 del contenedor al puerto 8888 de tu máquina local
    networks:
      - app-network
    depends_on:
      - discovery-service
    environment:
      SPRING_PROFILES_ACTIVE: local # Perfil activo en application.properties
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka/ # Apunta al discovery-service

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8989:8989"
    networks:
      - app-network
    depends_on:
      - config-server-bc
      - discovery-service
    environment:
      SPRING_PROFILES_ACTIVE: local # Perfil activo en application.properties
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka/ # Apunta al discovery-service

  business-service:
    build:
      context: ./business-service
      dockerfile: Dockerfile
    container_name: business-service
    ports:
      - "8585:8585"
    networks:
      - app-network
    depends_on:
      - config-server-bc
      - discovery-service
      - api-gateway
    environment:
      SPRING_PROFILES_ACTIVE: local # Perfil activo en application.properties
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka/ # Apunta al discovery-service

  service-product:
    build:
      context: ./service-product
      dockerfile: Dockerfile
    container_name: service-product
    ports:
      - "8383:8383"
    networks:
      - app-network
    depends_on:
      - config-server-bc
      - discovery-service
      - api-gateway
    environment:
      SPRING_PROFILES_ACTIVE: local # Perfil activo en application.properties
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka/ # Apunta al discovery-service

  service-customer:
    build:
      context: ./service-customer
      dockerfile: Dockerfile
    container_name: service-customer
    ports:
      - "8282:8282"
    networks:
      - app-network
    depends_on:
      - config-server-bc
      - discovery-service
      - api-gateway
    environment:
      SPRING_PROFILES_ACTIVE: local # Perfil activo en application.properties
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka/ # Apunta al discovery-service

  service-transaction:
    build:
      context: ./service-transaction
      dockerfile: Dockerfile
    container_name: service-transaction
    ports:
      - "8484:8484"
    networks:
      - app-network
    depends_on:
      - config-server-bc
      - discovery-service
      - api-gateway
    environment:
      SPRING_PROFILES_ACTIVE: local # Perfil activo en application.properties
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka/ # Apunta al discovery-service

  service-finance:
    build:
      context: ./service-finance
      dockerfile: Dockerfile
    container_name: service-finance
    ports:
      - "8686:8686"
    networks:
      - app-network
    depends_on:
      - config-server-bc
      - discovery-service
      - api-gateway
    environment:
      SPRING_PROFILES_ACTIVE: local # Perfil activo en application.properties
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka/ # Apunta al discovery-service

  resume-balance-bot:
    build:
      context: ./resume-balance-bot
      dockerfile: Dockerfile
    container_name: resume-balance-bot
    ports:
      - "8787:8787"
    networks:
      - app-network
    depends_on:
      - config-server-bc
      - discovery-service
      - api-gateway
    environment:
      SPRING_PROFILES_ACTIVE: local # Perfil activo en application.properties
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka/ # Apunta al discovery-service

  zookeeper:
    image: wurstmeister/zookeeper:latest
    networks:
      - app-network
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    networks:
      - app-network
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    networks:
      - app-network
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: "kafka:9092"
    depends_on:
      - kafka

  yanki-service:
    build:
      context: ../Yanki/yanki-service
      dockerfile: Dockerfile
    container_name: yanki-service
    networks:
      - app-network
    ports:
      - "9494:9494"
    environment:
      SPRING_PROFILES_ACTIVE: local # Configura el perfil activo de Spring
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE: http://discovery-service:8761/eureka/ # Apunta al discovery-service
    depends_on:
      - kafka

  users-service-api:
    build:
      context: ../Yanki/users-service-api
      dockerfile: Dockerfile
    container_name: users-service-api
    networks:
      - app-network
    ports:
      - "9191:9191" # Mapea el puerto del contenedor al host
    environment:
      SPRING_PROFILES_ACTIVE: local # Configura el perfil activo de Spring
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka

  wallet-service-api:
    build:
      context: ../Yanki/wallet-service-api
      dockerfile: Dockerfile
    container_name: wallet-service-api
    networks:
      - app-network
    ports:
      - "9292:9292" # Mapea el puerto del contenedor al host
    environment:
      SPRING_PROFILES_ACTIVE: local # Configura el perfil activo de Spring
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka

  movements-service-api:
    build:
      context: ../Yanki/movements-service-api
      dockerfile: Dockerfile
    container_name: movements-service-api
    networks:
      - app-network
    ports:
      - "9393:9393" # Mapea el puerto del contenedor al host
    environment:
      SPRING_PROFILES_ACTIVE: local # Configura el perfil activo de Spring
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka

networks:
  app-network:
    driver: bridge