spring.application.name=movements-service-api
server.port=9393

# Profile active
spring.profiles.active=local


management.endpoints.web.exposure.include=health,info

eureka.instance.instance-id=${spring.application.name}:${server.port}

spring.config.import=optional:configserver:
spring.cloud.config.discovery.service-id=config-server-bc


