spring.application.name=wallet-service-api
server.port=9292

# Profile active
spring.profiles.active=local

management.endpoints.web.exposure.include=health,info

eureka.instance.instance-id=${spring.application.name}:${server.port}

spring.config.import=optional:configserver:http://config-server-bc:8888
spring.cloud.config.discovery.service-id=config-server-bc


